apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: radix-oauth-guard
  annotations:
    github.com/project-slug: equinor/radix-oauth-guard
spec:
  type: other
  lifecycle: unknown
  owner: team-radix
