apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth-guard
  namespace: monitor
spec:
  selector:
    matchLabels:
      app: radix-oauth-guard
  template:
    metadata:
      labels:
        app: radix-oauth-guard
    spec:
      containers:
        - name: guard
          image: ghcr.io/equinor/radix-oauth-guard:v0.2.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          env:
            - name: LOG_PRETTY
              value: "True"
            - name: LOG_LEVEL
              value: debug
            - name: ISSUER
              value: https://northeurope.oic.prod-aks.azure.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/a2d93ba1-cbde-4408-8979-c100cce7b448/
            - name: AUDIENCE
              value: extmonprom
            - name: SUBJECTS
              value: system:serviceaccount:monitor:prometheus-operator-prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: oauth-guard
  namespace: monitor
spec:
  selector:
    app: radix-oauth-guard
  ports:
    - name: http
      port: 8000
