name: Pull request
on:
  pull_request:
    branches:
    - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.55.2

  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: Install dependencies
        run: go mod download
      - name: Run Tests
        run: go test -cover `go list ./... | grep -v 'pkg/client'`

  lint-helm:
    name: Lint Helm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@b7246b12e77f7134dc2d460a3d5bad15bbe29390 # v4.1.0

      - name: Helm Lint
        run: helm lint charts/radix-oauth-guard

  integration-test:
      name: Integration test
      runs-on: ubuntu-latest
      permissions:
        id-token: write
        contents: read
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v4
          with:
            go-version-file: 'go.mod'
        - name: Install dependencies
          run: go mod download
        - name: Test Auth
          env:
            LOG_PRETTY: True
            LOG_LEVEL: Trace
            ISSUER: "https://token.actions.githubusercontent.com"
            AUDIENCE: "https://github.com/equinor"
            SUBJECTS: repo:equinor/radix-oauth-guard:pull_request
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            go run . &
            GO_PID=$!
            sleep 2s
            CURL_RESPONSE=$(curl --write-out '%{http_code}' --output /dev/null  --header "Authorization: Bearer ${GH_TOKEN}" http://localhost:8000/auth)
            kill -9 $GO_PID
            echo "Curl status code: ${CURL_RESPONSE}!"
            :
            
